import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'eu' | 'fr' | 'de' | 'it' | 'zh' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    'app.title': 'Conversor de Motores FXM a FKM',
    'app.subtitle': 'Encuentra el motor FKM equivalente para tu motor FXM',
    'search.placeholder': 'Buscar motor FXM (ej: FXM 74.30A.xx.x10)',
    'search.button': 'Buscar',
    'results.title': 'Resultados de Conversión',
    'results.fxm': 'Motor FXM Original',
    'results.fkm': 'Motores FKM Equivalentes',
    'results.noResults': 'No se encontraron motores equivalentes',
    'report.generate': 'Generar Reporte',
    'report.pdf': 'Descargar PDF',
    'report.excel': 'Descargar Excel',
    'report.title': 'Reporte Comparativo de Conversión',
    'specs.electrical': 'Especificaciones Eléctricas',
    'specs.dimensions': 'Dimensiones Mecánicas',
    'specs.mo': 'Par a Rótor Parado (Mo)',
    'specs.mn': 'Par Nominal (Mn)',
    'specs.mp': 'Par de Pico (Mp)',
    'specs.io': 'Corriente a Rótor Parado (Io)',
    'specs.rpm': 'Velocidad Nominal',
    'specs.j': 'Inercia (J)',
    'specs.pcal': 'Potencia de Cálculo',
    'specs.l': 'Longitud Total (L)',
    'specs.ac': 'Ancho de Carcasa (AC)',
    'specs.n': 'Diámetro de Eje (N)',
    'specs.d': 'Diámetro de Brida (D)',
    'specs.e': 'Altura de Eje (E)',
    'specs.m': 'Longitud de Montaje (M)',
    'diff.label': 'Diferencia',
    'diff.percent': 'Cambio %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'rpm',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  en: {
    'app.title': 'FXM to FKM Motor Converter',
    'app.subtitle': 'Find the equivalent FKM motor for your FXM motor',
    'search.placeholder': 'Search FXM motor (e.g., FXM 74.30A.xx.x10)',
    'search.button': 'Search',
    'results.title': 'Conversion Results',
    'results.fxm': 'Original FXM Motor',
    'results.fkm': 'Equivalent FKM Motors',
    'results.noResults': 'No equivalent motors found',
    'report.generate': 'Generate Report',
    'report.pdf': 'Download PDF',
    'report.excel': 'Download Excel',
    'report.title': 'Conversion Comparison Report',
    'specs.electrical': 'Electrical Specifications',
    'specs.dimensions': 'Mechanical Dimensions',
    'specs.mo': 'Stall Torque (Mo)',
    'specs.mn': 'Rated Torque (Mn)',
    'specs.mp': 'Peak Torque (Mp)',
    'specs.io': 'Stall Current (Io)',
    'specs.rpm': 'Rated Speed',
    'specs.j': 'Inertia (J)',
    'specs.pcal': 'Calculation Power',
    'specs.l': 'Total Length (L)',
    'specs.ac': 'Housing Width (AC)',
    'specs.n': 'Shaft Diameter (N)',
    'specs.d': 'Flange Diameter (D)',
    'specs.e': 'Shaft Height (E)',
    'specs.m': 'Mounting Length (M)',
    'diff.label': 'Difference',
    'diff.percent': 'Change %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'rpm',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  eu: {
    'app.title': 'FXM-tik FKM-ra Motor Bihurtzailea',
    'app.subtitle': 'Aurkitu zure FXM motorrarentzako FKM motor baliokidea',
    'search.placeholder': 'Bilatu FXM motorra (adib: FXM 74.30A.xx.x10)',
    'search.button': 'Bilatu',
    'results.title': 'Bihurketa Emaitzak',
    'results.fxm': 'Jatorrizko FXM Motorra',
    'results.fkm': 'FKM Motor Baliokideak',
    'results.noResults': 'Ez da motor baliokiderik aurkitu',
    'report.generate': 'Txostena Sortu',
    'report.pdf': 'Deskargatu PDF',
    'report.excel': 'Deskargatu Excel',
    'report.title': 'Bihurketa Konparazio Txostena',
    'specs.electrical': 'Espezifikazio Elektrikoak',
    'specs.dimensions': 'Dimentsio Mekanikoak',
    'specs.mo': 'Momentua Geldirik (Mo)',
    'specs.mn': 'Momentu Nominala (Mn)',
    'specs.mp': 'Gailurreko Momentua (Mp)',
    'specs.io': 'Korronte Geldirik (Io)',
    'specs.rpm': 'Abiadura Nominala',
    'specs.j': 'Inertzia (J)',
    'specs.pcal': 'Kalkulu Potentzia',
    'specs.l': 'Luzera Osoa (L)',
    'specs.ac': 'Karkasaren Zabalera (AC)',
    'specs.n': 'Ardatzaren Diametroa (N)',
    'specs.d': 'Bridaren Diametroa (D)',
    'specs.e': 'Ardatzaren Altuera (E)',
    'specs.m': 'Muntatze Luzera (M)',
    'diff.label': 'Aldea',
    'diff.percent': 'Aldaketa %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'rpm',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  fr: {
    'app.title': 'Convertisseur de Moteurs FXM vers FKM',
    'app.subtitle': 'Trouvez le moteur FKM équivalent pour votre moteur FXM',
    'search.placeholder': 'Rechercher moteur FXM (ex: FXM 74.30A.xx.x10)',
    'search.button': 'Rechercher',
    'results.title': 'Résultats de Conversion',
    'results.fxm': 'Moteur FXM Original',
    'results.fkm': 'Moteurs FKM Équivalents',
    'results.noResults': 'Aucun moteur équivalent trouvé',
    'report.generate': 'Générer Rapport',
    'report.pdf': 'Télécharger PDF',
    'report.excel': 'Télécharger Excel',
    'report.title': 'Rapport Comparatif de Conversion',
    'specs.electrical': 'Spécifications Électriques',
    'specs.dimensions': 'Dimensions Mécaniques',
    'specs.mo': 'Couple à Rotor Bloqué (Mo)',
    'specs.mn': 'Couple Nominal (Mn)',
    'specs.mp': 'Couple de Pointe (Mp)',
    'specs.io': 'Courant à Rotor Bloqué (Io)',
    'specs.rpm': 'Vitesse Nominale',
    'specs.j': 'Inertie (J)',
    'specs.pcal': 'Puissance de Calcul',
    'specs.l': 'Longueur Totale (L)',
    'specs.ac': 'Largeur du Boîtier (AC)',
    'specs.n': 'Diamètre de l\'Arbre (N)',
    'specs.d': 'Diamètre de Bride (D)',
    'specs.e': 'Hauteur d\'Arbre (E)',
    'specs.m': 'Longueur de Montage (M)',
    'diff.label': 'Différence',
    'diff.percent': 'Changement %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'rpm',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  de: {
    'app.title': 'FXM zu FKM Motor Konverter',
    'app.subtitle': 'Finden Sie den äquivalenten FKM-Motor für Ihren FXM-Motor',
    'search.placeholder': 'FXM-Motor suchen (z.B. FXM 74.30A.xx.x10)',
    'search.button': 'Suchen',
    'results.title': 'Konvertierungsergebnisse',
    'results.fxm': 'Original FXM-Motor',
    'results.fkm': 'Äquivalente FKM-Motoren',
    'results.noResults': 'Keine äquivalenten Motoren gefunden',
    'report.generate': 'Bericht Erstellen',
    'report.pdf': 'PDF Herunterladen',
    'report.excel': 'Excel Herunterladen',
    'report.title': 'Vergleichsbericht zur Konvertierung',
    'specs.electrical': 'Elektrische Spezifikationen',
    'specs.dimensions': 'Mechanische Abmessungen',
    'specs.mo': 'Stillstandsmoment (Mo)',
    'specs.mn': 'Nennmoment (Mn)',
    'specs.mp': 'Spitzenmoment (Mp)',
    'specs.io': 'Stillstandsstrom (Io)',
    'specs.rpm': 'Nenndrehzahl',
    'specs.j': 'Trägheit (J)',
    'specs.pcal': 'Berechnungsleistung',
    'specs.l': 'Gesamtlänge (L)',
    'specs.ac': 'Gehäusebreite (AC)',
    'specs.n': 'Wellendurchmesser (N)',
    'specs.d': 'Flanschdurchmesser (D)',
    'specs.e': 'Wellenhöhe (E)',
    'specs.m': 'Montagelänge (M)',
    'diff.label': 'Unterschied',
    'diff.percent': 'Änderung %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'U/min',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  it: {
    'app.title': 'Convertitore Motori FXM a FKM',
    'app.subtitle': 'Trova il motore FKM equivalente per il tuo motore FXM',
    'search.placeholder': 'Cerca motore FXM (es: FXM 74.30A.xx.x10)',
    'search.button': 'Cerca',
    'results.title': 'Risultati Conversione',
    'results.fxm': 'Motore FXM Originale',
    'results.fkm': 'Motori FKM Equivalenti',
    'results.noResults': 'Nessun motore equivalente trovato',
    'report.generate': 'Genera Rapporto',
    'report.pdf': 'Scarica PDF',
    'report.excel': 'Scarica Excel',
    'report.title': 'Rapporto Comparativo di Conversione',
    'specs.electrical': 'Specifiche Elettriche',
    'specs.dimensions': 'Dimensioni Meccaniche',
    'specs.mo': 'Coppia a Rotore Bloccato (Mo)',
    'specs.mn': 'Coppia Nominale (Mn)',
    'specs.mp': 'Coppia di Picco (Mp)',
    'specs.io': 'Corrente a Rotore Bloccato (Io)',
    'specs.rpm': 'Velocità Nominale',
    'specs.j': 'Inerzia (J)',
    'specs.pcal': 'Potenza di Calcolo',
    'specs.l': 'Lunghezza Totale (L)',
    'specs.ac': 'Larghezza Alloggiamento (AC)',
    'specs.n': 'Diametro Albero (N)',
    'specs.d': 'Diametro Flangia (D)',
    'specs.e': 'Altezza Albero (E)',
    'specs.m': 'Lunghezza Montaggio (M)',
    'diff.label': 'Differenza',
    'diff.percent': 'Variazione %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'giri/min',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  zh: {
    'app.title': 'FXM 到 FKM 电机转换器',
    'app.subtitle': '为您的 FXM 电机找到等效的 FKM 电机',
    'search.placeholder': '搜索 FXM 电机（例如：FXM 74.30A.xx.x10）',
    'search.button': '搜索',
    'results.title': '转换结果',
    'results.fxm': '原始 FXM 电机',
    'results.fkm': '等效 FKM 电机',
    'results.noResults': '未找到等效电机',
    'report.generate': '生成报告',
    'report.pdf': '下载 PDF',
    'report.excel': '下载 Excel',
    'report.title': '转换对比报告',
    'specs.electrical': '电气规格',
    'specs.dimensions': '机械尺寸',
    'specs.mo': '堵转转矩 (Mo)',
    'specs.mn': '额定转矩 (Mn)',
    'specs.mp': '峰值转矩 (Mp)',
    'specs.io': '堵转电流 (Io)',
    'specs.rpm': '额定转速',
    'specs.j': '惯量 (J)',
    'specs.pcal': '计算功率',
    'specs.l': '总长度 (L)',
    'specs.ac': '机壳宽度 (AC)',
    'specs.n': '轴直径 (N)',
    'specs.d': '法兰直径 (D)',
    'specs.e': '轴高度 (E)',
    'specs.m': '安装长度 (M)',
    'diff.label': '差异',
    'diff.percent': '变化 %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': '转/分',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
  pt: {
    'app.title': 'Conversor de Motores FXM para FKM',
    'app.subtitle': 'Encontre o motor FKM equivalente para o seu motor FXM',
    'search.placeholder': 'Pesquisar motor FXM (ex: FXM 74.30A.xx.x10)',
    'search.button': 'Pesquisar',
    'results.title': 'Resultados da Conversão',
    'results.fxm': 'Motor FXM Original',
    'results.fkm': 'Motores FKM Equivalentes',
    'results.noResults': 'Nenhum motor equivalente encontrado',
    'report.generate': 'Gerar Relatório',
    'report.pdf': 'Baixar PDF',
    'report.excel': 'Baixar Excel',
    'report.title': 'Relatório Comparativo de Conversão',
    'specs.electrical': 'Especificações Elétricas',
    'specs.dimensions': 'Dimensões Mecânicas',
    'specs.mo': 'Torque com Rotor Parado (Mo)',
    'specs.mn': 'Torque Nominal (Mn)',
    'specs.mp': 'Torque de Pico (Mp)',
    'specs.io': 'Corrente com Rotor Parado (Io)',
    'specs.rpm': 'Velocidade Nominal',
    'specs.j': 'Inércia (J)',
    'specs.pcal': 'Potência de Cálculo',
    'specs.l': 'Comprimento Total (L)',
    'specs.ac': 'Largura da Carcaça (AC)',
    'specs.n': 'Diâmetro do Eixo (N)',
    'specs.d': 'Diâmetro do Flange (D)',
    'specs.e': 'Altura do Eixo (E)',
    'specs.m': 'Comprimento de Montagem (M)',
    'diff.label': 'Diferença',
    'diff.percent': 'Mudança %',
    'unit.nm': 'Nm',
    'unit.arms': 'Arms',
    'unit.rpm': 'rpm',
    'unit.kgcm2': 'kg/cm²',
    'unit.kw': 'kW',
    'unit.mm': 'mm',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');
  
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
